### ISSUE TITLE
vite启动报错

### ISSUE THREAD

**Issue by Nakus0426** [GitOfZGT/vite-plugin-theme-preprocessor#1]
引入后启动项目报错：
![image](https://user-images.githubusercontent.com/41540888/131478094-cd6a7f71-7a57-44a6-9357-8c5c75849d30.png)
是不是less版本过高？还是因为我没装less-loader（装和没装都报这个错误）
安装方式：npm
node版本：14.17.3
vite版本：2.5.0
less版本：4.1.1
vue版本：3.2.4

**Comment by Nakus0426** [comment]
这是配置的内容和目录结构
![image](https://user-images.githubusercontent.com/41540888/131483584-d1eb09a0-bea3-4c0b-bb1c-858280727533.png)

**Comment by GitOfZGT** [comment]
由于.gitignore导致less处理文件丢失，v1.1.1 找回修复报错问题

**Comment by Nakus0426** [comment]
> 由于.gitignore导致less处理文件丢失，v1.1.1 找回修复报错问题

所以less-loader需要装吗？还是说插件已经替换了不需要

**Comment by GitOfZGT** [comment]
> 所以less-loader需要装吗？还是说插件已经替换了不需要

less-loader用于webpack，在vite不需要装

**Comment by Nakus0426** [comment]
> > 所以less-loader需要装吗？还是说插件已经替换了不需要
> 
> less-loader用于webpack，在vite不需要装
