### ISSUE TITLE
`rel="stylesheet"` missing on build

### ISSUE THREAD

**Issue by naftis** [GitOfZGT/vite-plugin-theme-preprocessor#10]
![image](https://user-images.githubusercontent.com/1322608/141019104-56fc8ea6-bfbe-4344-b5e6-96946054f79f.png)
Link tag doesn't have `rel="stylesheet"` attribute on build which makes it not load for me on Google Chrome.

**Comment by GitOfZGT** [comment]
exactly，@zougt/vite-plugin-theme-preprocessor v1.3.8 has fixed.

**Comment by naftis** [comment]
Thank you, this seems to have fixed it for me!
