### ISSUE TITLE
vite-plugin-theme-preprocessor and ElementPlus

### ISSUE THREAD

**Issue by naftis** [GitOfZGT/vite-plugin-theme-preprocessor#11]
I'm not sure if this is an issue of the library but I'm having problems when using this with ElementPlus.

**Example repository:** https://github.com/naftis/element-plus-theming (based on this: https://github.com/element-plus/element-plus-vite-starter)
**Error**: Some CSS variables don't get loaded
![image](https://user-images.githubusercontent.com/1322608/142395417-18fe4b9c-4808-4bba-ba1f-5a1025434462.png)

How should I configure ElementPlus to work with this library? I load this file in `multipleScopeVars`: https://github.com/naftis/element-plus-theming/blob/master/src/styles/theme/default.scss with `@forward` but all of the CSS variables don't load.
It seems like every variable changed in `@forward` seem to get unloaded.

**Comment by GitOfZGT** [comment]
Thanks for your feedback.
I fixed it in @zougt/some-loader-utils v1.3.5,Please reinstall @zougt/vite-plugin-theme-preprocessor.
![image](https://user-images.githubusercontent.com/21262000/142449441-4d3d7964-bed2-4826-a7ff-8b4100dac339.png)

**Comment by naftis** [comment]
Hello, example repository: https://github.com/naftis/element-plus-theming
For some reason it doesn't work properly when changing the theme here:
![image](https://user-images.githubusercontent.com/1322608/145816654-ce701260-3312-4d91-8fe1-3702d72d3025.png)

The background should go black, and the "Tag 1" has undefined CSS variables 🤔 
![image](https://user-images.githubusercontent.com/1322608/145816737-4034c0c7-c2e6-4923-a185-8444926f3222.png)

Thank you very much for help.

**Comment by GitOfZGT** [comment]
You should use `toggleTheme` on this way:

![image](https://user-images.githubusercontent.com/21262000/145821904-a1a8d412-964f-4107-b970-6175f9b3b502.png)

To

![image](https://user-images.githubusercontent.com/21262000/145821778-580972e1-995c-4abd-bf43-0589e93df158.png)

**Comment by naftis** [comment]
@GitOfZGT Thank you :) 

https://goofy-booth-e1e803.netlify.app/ the element-plus primary color works in the navigation:
![image](https://user-images.githubusercontent.com/1322608/145828613-6a151c6b-689f-4f35-8126-3beb1b53bb8e.png)
![image](https://user-images.githubusercontent.com/1322608/145828634-246538d6-0aa0-4aee-b259-4738c84b6b1c.png)

There is another issue though, the Button colors don't change to pink:
![image](https://user-images.githubusercontent.com/1322608/145829254-eccdeef2-05ed-4118-9492-49de2b6ba75b.png)
![image](https://user-images.githubusercontent.com/1322608/145828930-52cd076e-3867-40c8-a60b-6edffada4e9a.png)

It seems to add the variables to `style` -attribute:
![image](https://user-images.githubusercontent.com/1322608/145829095-f1a9a25a-3178-4fc5-938d-3f13e7ae3326.png)
Do you think this is element-plus issue or vite-plugin-theme-preprocessor issue?

**Comment by GitOfZGT** [comment]
> element-plus issue or vite-plugin-theme-preprocessor issue?

I also found this problem some time ago, that is element-plus did, theme plugin can not change it, see [https://github.com/element-plus/element-plus/issues/4263](https://github.com/element-plus/element-plus/issues/4263)
