### ISSUE TITLE
报个操作不允许错误

### ISSUE THREAD

**Issue by chinapostm** [GitOfZGT/vite-plugin-theme-preprocessor#12]
环境
    "OS": "WIN10",
    "@vitejs/plugin-vue": "^1.9.3",
    "@zougt/vite-plugin-theme-preprocessor": "^1.3.12",
    "less": "^4.1.2",
    "sass": "^1.43.4",
    "stylus":  #"^0.55.0",
    "vite": "^2.6.4",
    "ant-design-vue": "^2.2.8",
    "path": "^0.12.7",
    "vue": "^3.2.16"

![20211123051304](https://user-images.githubusercontent.com/75209261/142936538-645f4450-5c8a-4e2a-8b0d-48fc154d98f2.png)
![微信截图_20211123051839](https://user-images.githubusercontent.com/75209261/142936687-b1727069-0b85-4186-82c2-20b6bb405807.png)

**Comment by GitOfZGT** [comment]
可能是cnpm创建的快捷链接让fs-extra的方法没有权限， 弃用cnpm吧，yarn 或者 pnpm

https://github.com/jprichardson/node-fs-extra/issues/726

**Comment by chinapostm** [comment]
感谢 方法有效
