### ISSUE TITLE
集成ant-design-vue主题切换时按钮颜色不正确

### ISSUE THREAD

**Issue by gas0324** [GitOfZGT/vite-plugin-theme-preprocessor#14]
primary按钮的文字颜色应为白色，当前是黑色
![1](https://user-images.githubusercontent.com/14065807/143518786-0bb9244f-de4d-42ba-bb00-2888cd1d341e.jpg)
![2](https://user-images.githubusercontent.com/14065807/143518791-78d04f8a-bd42-4d36-9844-32f6bc545b5f.jpg)
我查看到是因为这个css的问题
![3](https://user-images.githubusercontent.com/14065807/143518939-b88c92f5-5ff5-4401-95b6-ffef43aad5c6.jpg)
这里是我做的demo
[theme-test.zip](https://github.com/GitOfZGT/vite-plugin-theme-preprocessor/files/7605973/theme-test.zip)

**Comment by gas0324** [comment]
或者说.theme-default .ant-btn-primary 中应该增加 color: #fff

**Comment by GitOfZGT** [comment]
这种情况目前的实现方式无法自动避免， 你参考文档的这个属性说明
![image](https://user-images.githubusercontent.com/21262000/143535120-8ab2897b-9211-41ba-b397-80037c43ec1a.png)

**Comment by gas0324** [comment]
好的

**Comment by gas0324** [comment]
![QQ截图20211126171926](https://user-images.githubusercontent.com/14065807/143557132-e28910e0-ceac-45e9-9447-c84eb511f3c4.jpg)
这里不能使用变量吗？

**Comment by GitOfZGT** [comment]
> ![QQ截图20211126171926](https://user-images.githubusercontent.com/14065807/143557132-e28910e0-ceac-45e9-9447-c84eb511f3c4.jpg) 这里不能使用变量吗？

不行的哦，那里处理的是css， 不是less了，你想这样就写在某个less文件内覆盖组件库的样式就可以，也没必要写在这里

**Comment by gas0324** [comment]
谢谢，我最终这样解决问题。
![QQ截图20211127102530](https://user-images.githubusercontent.com/14065807/143665297-5c1d1ec4-7b41-40f2-b05f-3a2c0232c1d1.jpg)
但是我发现这样写所产生的css里面没有主题类名，所以，我是否有其他的方法可以让css增加主题类名，就像includeStyles那样，或者说是否可以提供一个includeStyleFile，引入对应的文件，文件中的内容都增加主题类名。

**Comment by gas0324** [comment]
或者说这样的语法
```js
import themePreprocessorPlugin from "@zougt/vite-plugin-theme-preprocessor";
export default {
  plugins: [
    themePreprocessorPlugin({
      scss: {
      // 预处理器的变量文件
      less: {
        multipleScopeVars: [
          {
            scopeName: "theme-default",
            files: [
              {
                path: path.resolve("src/theme/default-vars.less"),
                forceThemeClass: false    // 默认
              },
              {
                path: path.resolve("src/theme/default-vars1.less"),
                forceThemeClass: true    // true
              },
            ]
          },
          {
            scopeName: "theme-mauve",
            files: [
              {
                path: path.resolve("src/theme/mauve-vars.less"),
              }
            ]
          },
        ],
      },
    }),
  ],
};
```

**Comment by GitOfZGT** [comment]
不需要这样，可以参考这个回复。 #15

**Comment by GitOfZGT** [comment]
v1.4.0 新增属性可以更方便的解决权重问题
![image](https://user-images.githubusercontent.com/21262000/144783295-692dc8ab-cc7b-4ed2-a125-adb721b8d8e0.png)

**Comment by gas0324** [comment]
谢谢，下午我试一下
