### ISSUE TITLE
使用了antdesign 默认和 dark主题进行切换 打包的时候提示 Maximum call stack size exceeded

### ISSUE THREAD

**Issue by leemy15** [GitOfZGT/vite-plugin-theme-preprocessor#15]
![image](https://user-images.githubusercontent.com/32156656/143835192-66a205bc-b89f-4b24-88bf-36b3f49e143c.png)

![image](https://user-images.githubusercontent.com/32156656/143835145-61e1c773-1023-4388-856d-aae5266f31a6.png)

![image](https://user-images.githubusercontent.com/32156656/143835193-b24073c3-eb27-4ded-84c0-6dbc70678a1f.png)
自己写的一个demo 开发环境没问题 打包就报错

**Comment by GitOfZGT** [comment]
请不要在 multipleScopeVars 的变量文件夹带样式代码，设定上只需存在对比的变量，@import "ant-design-vue/dist/antd.less" 这种带有样式的文件不应该写在这，而且会全量引入所有组件的样式，不建议这样使用，此插件不是编译主题，还更好的让组件库的样式按需，使用vue的，推荐 [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components) 按需引入组件并且按需引入对应的less。

提供参考：
![image](https://user-images.githubusercontent.com/21262000/143891565-f92b717b-bdc2-4752-b76a-9a6aa1f53067.png)

**Comment by leemy15** [comment]
好的解决了 谢谢大佬 我引入的包不太对 应该引入变量的
