### ISSUE TITLE
Internal server error: Preprocessor dependency "less" not found. Did you install it?

### ISSUE THREAD

**Issue by PathFun** [GitOfZGT/vite-plugin-theme-preprocessor#16]
"less": "4.1.2",
 "less-loader": "10.2.0",
 "vite": "2.6.14",
 "ant-design-vue": "^3.0.0-alpha.13",

**Comment by GitOfZGT** [comment]
这种情况，删除node_modules,重新安装试试了， 尽量不用cnpm， 如果还不行，报告下使用的插件版本，或者提供demo咯

**Comment by 434451580** [comment]
似乎我也遇到这个问题了,配置  
 css: {
    preprocessorOptions: {
      less: {
        // 支持内联 JavaScript
        javascriptEnabled: true
      }
    }
  }
解决

**Comment by 434451580** [comment]
@PathFun 似乎我也遇到这个问题了,配置
css: {
preprocessorOptions: {
less: {
// 支持内联 JavaScript
javascriptEnabled: true
}
}
}
解决

**Comment by GitOfZGT** [comment]
> @PathFun 似乎我也遇到这个问题了,配置 css: { preprocessorOptions: { less: { // 支持内联 JavaScript javascriptEnabled: true } } } 解决


缺少 javascriptEnabled: true 应该是报这种错误，他描述的是less包找不到
![image](https://user-images.githubusercontent.com/21262000/144579216-5f91f44b-e74b-44c8-b889-d80383002df7.png)

**Comment by transtone** [comment]
> @PathFun 似乎我也遇到这个问题了,配置 css: { preprocessorOptions: { less: { // 支持内联 JavaScript javascriptEnabled: true } } } 解决

这段配置一直是有的，但就是报错。

**Comment by GitOfZGT** [comment]
在 v1.4.0.beta.5 修复， 安装新版本前，先删除一次node_modules, 最好yarn.lock 也删除一次。

**Comment by transtone** [comment]
> 在 v1.4.0.beta.5 修复， 安装新版本前，先删除一次node_modules, 最好yarn.lock 也删除一次。

已更新到beta.5 ，已删除 node_modues 和 yarn.lock，但此问题仍在。

**Comment by GitOfZGT** [comment]
> 复现仓库：
> 
> https://github.com/transtone/-vite-plugin-theme-preprocessor-debug

提供的demo并未浮现上面的报错，只发现这个normal.less 文件不存在报错
![在这里插入图片描述](https://img-blog.csdnimg.cn/b4367c2b300d4899bb01048a35db4102.gif)

并且
![image](https://user-images.githubusercontent.com/21262000/144736622-464f7b75-a886-4045-ae10-8102dcc11853.png)

**Comment by GitOfZGT** [comment]
> > 复现仓库：
> > https://github.com/transtone/-vite-plugin-theme-preprocessor-debug
> 
> 提供的demo并未浮现上面的报错，只发现这个normal.less 文件不存在报错 ![在这里插入图片描述](https://img-blog.csdnimg.cn/8848875ec3e2401888c1667e5435234a.gif)
> 
> 并且 ![image](https://user-images.githubusercontent.com/21262000/144736622-464f7b75-a886-4045-ae10-8102dcc11853.png)

**Comment by GitOfZGT** [comment]
或许可能是 node版本和 npm版本有差异，待测试

**Comment by transtone** [comment]
`node-v16.13.0`
