### ISSUE TITLE
linux 下编译报错

### ISSUE THREAD

**Issue by transtone** [GitOfZGT/vite-plugin-theme-preprocessor#18]
```shell
❯ yarn build
yarn run v1.22.17
$ vite build
vite v2.6.14 building for production...
✓ 0 modules transformed.
[vite-plugin-theme-preprocessor] ENOENT: no such file or directory, stat '/mnt/d/code/hnrr/FE/pc-grid/node_modules/@zougt/vite-plugin-theme-preprocessor/dist/substitute/less/node_modules/.bin/needle'
error during build:
Error: ENOENT: no such file or directory, stat '/mnt/d/code/hnrr/FE/pc-grid/node_modules/@zougt/vite-plugin-theme-preprocessor/dist/substitute/less/node_modules/.bin/needle'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

版本 1.3.12，`node-v16.13.1`

**Comment by GitOfZGT** [comment]
在 v1.4.0.beta.5 修复， 安装新版本前，先删除一次node_modules, 最好yarn.lock 也删除一次。

**Comment by transtone** [comment]
@GitOfZGT  作者你好，能不能先把 1.3.x 修一下？
现在的情况是 v1.3.x 在 windows 下能用，但在 linux 下报错（编译需要）。
而 v1.4.x 在 windows 下报错，在 linux 下可用。

完全没法用呀。

**Comment by GitOfZGT** [comment]
> @GitOfZGT 作者你好，能不能先把 1.3.x 修一下？ 现在的情况是 v1.3.x 在 windows 下能用，但在 linux 下报错（编译需要）。 而 v1.4.x 在 windows 下报错，在 linux 下可用。
> 
> 完全没法用呀。

稍等，我写个demo放上来，在处理中

**Comment by GitOfZGT** [comment]
[https://github.com/GitOfZGT/dynamic-theme-demos](https://github.com/GitOfZGT/dynamic-theme-demos)
请用你的环境跑下这里的demo
目录：projects/vite-antd-vue-preset-theme
![在这里插入图片描述](https://img-blog.csdnimg.cn/caa3ccb9949a4fc4a6a8c7442291ed07.gif

**Comment by GitOfZGT** [comment]
> https://github.com/GitOfZGT/dynamic-theme-demos 请用你的环境跑下这里的demo 目录：projects/vite-antd-vue-preset-theme ![在这里插入图片描述](https://img-blog.csdnimg.cn/caa3ccb9949a4fc4a6a8c7442291ed07.gif)

**Comment by transtone** [comment]
![image](https://user-images.githubusercontent.com/46688/144744437-31639179-8db6-4306-b0b5-c8134f810bdc.png)

**Comment by GitOfZGT** [comment]
哭了，到底环境相差在哪呢

**Comment by GitOfZGT** [comment]
能否找到这个位置把 错误输出来看看是什么
![image](https://user-images.githubusercontent.com/21262000/144745508-ab4748b0-6eb1-40ef-910b-a9911c41bb9d.png)
然后看看node_modules 能不能找的less包，截个图
![image](https://user-images.githubusercontent.com/21262000/144745542-844722d0-171a-44f7-9285-c59d0e8b627f.png)

**Comment by transtone** [comment]
![image](https://user-images.githubusercontent.com/46688/144746116-707c1b38-4276-4c95-856a-fdea83a44933.png)

**Comment by transtone** [comment]
![image](https://user-images.githubusercontent.com/46688/144746771-992b33f8-c50e-47cc-a6e2-4a681214c343.png)

这是什么鬼，node_modules 目录下的 less 怎么变这样了？

**Comment by GitOfZGT** [comment]
我知道了怎么回事了， v1.4.0-beta.9 可以了

**Comment by transtone** [comment]
经测试，windows下可用；linux 也可用。👍
