### ISSUE TITLE
编译后样式失常

### ISSUE THREAD

**Issue by transtone** [GitOfZGT/vite-plugin-theme-preprocessor#19]
dev开发环境下面包屑和提示框的样式都是正常的，但编译后就不正常了，黑色主题显示白色的样式。

**Comment by GitOfZGT** [comment]
这个要提供demo看看， 因为主题打包抽取了独立文件有可能会打乱顺序导致权重问题

**Comment by transtone** [comment]
https://github.com/transtone/-vite-plugin-theme-preprocessor-debug
这是一个可以复现问题的demo

能不能帮忙看看这里的配置是否正常？

**Comment by transtone** [comment]
![image](https://user-images.githubusercontent.com/46688/144750702-cc06d8a1-3c27-4f85-8951-7ac435d3ee4a.png)

比如这个样式，开发模式是有的，但编译之后就不见了。

**Comment by GitOfZGT** [comment]
> https://github.com/transtone/-vite-plugin-theme-preprocessor-debug 这是一个可以复现问题的demo，用 serve dist 看，和 yarn dev 看效果不一样，dev下是正常的。
> 
> 能不能帮忙看看这里的配置是否正常？

你的vite.config.js 没有 extract:false ， 因为它默认是true， 不想抽取就false
![image](https://user-images.githubusercontent.com/21262000/144751091-7b097498-48e0-4d4c-8e77-02be91900960.png)

你可以引入我写好的 toggleTheme 就不用考虑了，都处理好的了
![image](https://user-images.githubusercontent.com/21262000/144751176-6e235d4c-36dc-4a7d-abc8-4d9f159bc485.png)

**Comment by GitOfZGT** [comment]
> 果然只引入了一个。

抽取到独立的css文件，只引入一个是正常，每次toggleTheme就需要加载对应的css文件哦

**Comment by transtone** [comment]
必须用
`import { toggleTheme } from "@zougt/vite-plugin-theme-preprocessor/dist/browser-utils"`
这个方法，否则无效。建议在文档中强调一下。

**Comment by GitOfZGT** [comment]
> 必须用 `import { toggleTheme } from "@zougt/vite-plugin-theme-preprocessor/dist/browser-utils"` 这个方法，否则无效。建议在文档中强调一下。

也不是必须用，只是提供了默认可用的方法
