### ISSUE TITLE
集成ant-design-vue主题切换时出现多余的样式

### ISSUE THREAD

**Issue by Nakus0426** [GitOfZGT/vite-plugin-theme-preprocessor#2]
在使用less模式后切换主题会出现不知名的样式。
theme-default时：
![image](https://user-images.githubusercontent.com/41540888/131983978-58b2614b-9af2-4566-a415-3884cd3163ec.png)
theme-dark时：
![image](https://user-images.githubusercontent.com/41540888/131983872-e5767a0a-5419-4d8c-8b3a-401dc7a8bb97.png)

下面是两个自定义主题文件的内容
![image](https://user-images.githubusercontent.com/41540888/131984161-2c36ee77-354b-4306-93bf-4b2bd0840e50.png)
![image](https://user-images.githubusercontent.com/41540888/131984186-765efb9f-583e-493d-97ea-11c3a88a1b19.png)

下面是插件配置
![image](https://user-images.githubusercontent.com/41540888/131984250-cdefa85a-872d-41d7-b194-4dc5312d2177.png)

**Comment by GitOfZGT** [comment]
删除yarn.lock或package-lock.json之类的重新安装依赖，得到最新依赖 @zougt/some-loader-utils v1.2.1,  已修复出现多余的非主题样式
![Uploading image.png…]()

**Comment by GitOfZGT** [comment]
删除yarn.lock或package-lock.json之类再重新安装依赖，得到最新依赖 @zougt/some-loader-utils v1.2.1, 已修复出现多余的非主题样式
![image](https://user-images.githubusercontent.com/21262000/132089374-845193a4-bd67-4711-9fee-bc4898ca11a7.png)

**Comment by Nakus0426** [comment]
> 删除yarn.lock或package-lock.json之类再重新安装依赖，得到最新依赖 @zougt/some-loader-utils v1.2.1, 已修复出现多余的非主题样式
> ![image](https://user-images.githubusercontent.com/21262000/132089374-845193a4-bd67-4711-9fee-bc4898ca11a7.png)

未发现最新的1.2.1版本..

**Comment by Nakus0426** [comment]
已解决，感谢
