### ISSUE TITLE
scss怎么好像不起作用呢 vite2.6.4

### ISSUE THREAD

**Issue by wishong** [GitOfZGT/vite-plugin-theme-preprocessor#20]
根据文档来的 但是感觉文档不是很清楚 麻烦看下这是为啥
![QQ图片20211205215743](https://user-images.githubusercontent.com/53365470/144749593-3895bd17-eaad-4bff-9b4f-1b84f4be397c.png)
![QQ图片20211205215825](https://user-images.githubusercontent.com/53365470/144749607-9bd8fc52-16fd-4978-b849-7fc1f2892c83.png)
![QQ图片20211205215851](https://user-images.githubusercontent.com/53365470/144749609-c87fe443-6f81-4844-b834-0542015a018e.png)

**Comment by GitOfZGT** [comment]
嗯可能文档描述不清楚，还需继续完善，**预设主题模式**需要多个变量文件，这是关键的，因为你选用的编译多份不同的主题

**Comment by wishong** [comment]
> 嗯可能文档描述不清楚，还需继续完善，**预设主题模式**需要多个变量文件，这是关键的，因为你选用的编译多份不同的主题

您可以提供一个scss的demo吗？我尝试增加了多个变量文件也不行。修改了您提供的less demo为scss也不生效

**Comment by GitOfZGT** [comment]
> 您可以提供一个scss的demo吗？我尝试增加了多个变量文件也不行。修改了您提供的less demo为scss也不生效

可以的，看表单效果
[在线demo](https://gitofzgt.github.io/dynamic-theme-demos/vite-element-plus-preset-theme/).  
[demo源码](https://github.com/GitOfZGT/dynamic-theme-demos/tree/master/projects/vite-element-plus-preset-theme).

**Comment by wishong** [comment]
> 可以的，看表单效果 [在线demo](https://gitofzgt.github.io/dynamic-theme-demos/vite-element-plus-preset-theme/). [demo源码](https://github.com/GitOfZGT/dynamic-theme-demos/tree/master/projects/vite-element-plus-preset-theme).

是不是antd无法使用scss的方式 我看您element需要先引入scss样式才能修改
![QQ图片20211206093500](https://user-images.githubusercontent.com/53365470/144773722-3c45438d-a779-4989-901d-e40fbf361c24.png)

**Comment by wishong** [comment]
> 可以的，看表单效果 [在线demo](https://gitofzgt.github.io/dynamic-theme-demos/vite-element-plus-preset-theme/). [demo源码](https://github.com/GitOfZGT/dynamic-theme-demos/tree/master/projects/vite-element-plus-preset-theme).

是不是antd无法使用scss的方式修改了，我看您的demo element是需要先引入scss样式的。但是antd好像只提供了css和less的样式
![QQ图片20211206093500](https://user-images.githubusercontent.com/53365470/144773802-5cba08c7-2b52-487e-b7a0-3f267d1036b6.png)

**Comment by GitOfZGT** [comment]
> 是不是antd无法使用scss的方式修改了，我看您的demo element是需要先引入scss样式的。但是antd好像只提供了css和less的样式 

antd使用的less， 你想组件库用less，自己源码用scss， 两种css处理器混用吗，这种情况按理也是可以，主要是未尝试过

**Comment by GitOfZGT** [comment]
> 是不是antd无法使用scss的方式修改了，我看您的demo element是需要先引入scss样式的。但是antd好像只提供了css和less的样式 

antd使用的less， 你想组件库用less，自己源码用scss， 两种css处理器混用吗，这种情况按理也是可以，主要是未尝试过

**Comment by wishong** [comment]
> antd使用的less， 你想组件库用less，自己源码用scss， 两种css处理器混用吗，这种情况按理也是可以，主要是未尝试过

是的 我目前用的是antd 2.x，然后想用scss的方式去修改antd的主题，但是好像是行不通的。用less倒是可以

**Comment by GitOfZGT** [comment]
> 是的 我目前用的是antd 2.x，然后想用scss的方式去修改antd的主题，但是好像是行不通的。用less倒是可以

[less+scss同时使用](https://github.com/GitOfZGT/dynamic-theme-demos/tree/master/projects/vite-less-scss-together-preset-theme)

**Comment by wishong** [comment]
> [less+scss同时使用](https://github.com/GitOfZGT/dynamic-theme-demos/tree/master/projects/vite-less-scss-together-preset-theme)

这个demo实际上还是less在起作用，把scss的配置对象注释掉，antd主题仍然会变化。但是less对象注释掉之后，antd主题就不会变化了。

**Comment by GitOfZGT** [comment]
> 这个demo实际上还是less在起作用，把scss的配置对象注释掉，antd主题仍然会变化。但是less对象注释掉之后，antd主题就不会变化了。
这是当然，两种处理器就需要两种对应的配置，能做到的也只是共用同名称的简单 变量，因为less编译不了scss，同理scss编译不了less， 将他们职责分清，less针对antd， scss 专注当前src，能做到就这些了。

**Comment by wishong** [comment]
> 这是当然，两种处理器就需要两种对应的配置，能做到的也只是共用同名称的简单 变量，因为less编译不了scss，同理scss编译不了less， 将他们职责分清，less针对antd， scss 专注当前src，能做到就这些了。

好的 非常感谢
