### ISSUE TITLE
vite+ts+vue3启动不起来

### ISSUE THREAD

**Issue by balck-paint** [GitOfZGT/vite-plugin-theme-preprocessor#21]
不支持ts吗？vite一直在加载。要不就报错要不就一直加载中，项目启动不起来

**Comment by GitOfZGT** [comment]
是否文档提供的demo运行不了，还是其他项目？  看看这个 [https://github.com/GitOfZGT/vite-dynamictheme-antd-vue-demo](https://github.com/GitOfZGT/vite-dynamictheme-antd-vue-demo)， 就是ts的

**Comment by Anunnakill** [comment]
> 



> 不支持ts吗？vite一直在加载。要不就报错要不就一直加载中，项目启动不起来

支持的。完美运行vite 我的工程也是vite+ts+vue3全家桶，完美支持，已经部署上线了，目前没有任何问题呢，你是否按照教程一步一步写的？

**Comment by balck-paint** [comment]
@Anunnakill  你是预设主题还是动态主题，我用的是预设主题，是按照他的示例demo配的

**Comment by balck-paint** [comment]
@GitOfZGT 是否有预设主题ts的demo？

**Comment by balck-paint** [comment]
@GitOfZGT 可以了。请问这个预设主题和动态主题可以同时使用吗

**Comment by GitOfZGT** [comment]
> @GitOfZGT 可以了。请问这个预设主题和动态主题可以同时使用吗
@balck-paint  目前是不能的，设想上能够做到，实现上有点复杂，考虑后续版本尝试实现。
