### ISSUE TITLE
主题文件里面定义相同的变量会导致样式错误

### ISSUE THREAD

**Issue by Mohaiyo** [GitOfZGT/vite-plugin-theme-preprocessor#22]
# 主题文件定义相同变量导致样式错误

## 主题文件
theme-default.less

```less
@import 'ant-design-vue/lib/style/themes/default.less';
@primary-color: #41b883;
@link-color: #485fc7;
@success-color: #06d6a0;
@warning-color: #faae42;

@error-color: #e62965;
```

theme-dark.less
```less
@import 'ant-design-vue/lib/style/themes/dark.less';
@primary-color: #41b883;
```
上面两个主题文件定义了相同的primary-color变量@primary-color: #41b883; 会导致样式错误
![image](https://user-images.githubusercontent.com/22421509/146333924-c5cbee13-5a6f-4452-8a78-0709795d4e4f.png)

## 重现步骤
修改[预设主题demo](https://github.com/GitOfZGT/dynamic-theme-demos/tree/master/projects/vite-antd-vue-preset-theme#%E9%A2%84%E8%AE%BE%E4%B8%BB%E9%A2%98demo)可以复现

**Comment by GitOfZGT** [comment]
把 #41b883 加入 includeStyleWithColors ， 或者  移除 includeStyleWithColors 的 #ffffff ， 都是样式权重问题
```js
 {
includeStyleWithColors: [
          {
            color: ["#ffffff","#41b883"],
            // 排除掉样式属性，这里将非背景的白色提升权重
            excludeCssProps: ["background", "background-color"],
            // 此类颜色的是否跟随主题色梯度变化，默认false
            // inGradient: true,
          },
        ],
}
```

**Comment by Mohaiyo** [comment]
好的 谢谢
