### ISSUE TITLE
demo 失效了

### ISSUE THREAD

**Issue by qingtiantongxie** [GitOfZGT/vite-plugin-theme-preprocessor#24]
https://gitofzgt.github.io/dynamic-theme-demos/vite-antd-vue-preset-theme/ 这个demo  没有效果  我下载以后启动在本地  没有报错  但是切换主题也不生效   看了下demo  不知道是哪里的问题  toggleTheme 好像没有执行

**Comment by GitOfZGT** [comment]
我用macOS未发现，用windows确实重现了toggleTheme不起作用，@zougt/vite-plugin-theme-preprocessor v1.4.3  已修复
