### ISSUE TITLE
有几个问题咨询一下

### ISSUE THREAD

**Issue by AnyFork** [GitOfZGT/vite-plugin-theme-preprocessor#25]
1内置主题和动态主题不能同时使用吗？
2动态主题设置的default.less文件中，添加额外全局属性，例如：ant desin vue 里面的@body-background: #eee;启动服务，通过命令：
npx z-theme inspect，为什么颜色没有包含在 gradientReplacer: { '#512da7': '#512da7', '#6d1414': '#6d1414' }之中，反复重启，莫名其妙的加入了一个，其他颜色属性没有加入，通过setCustomTheme()设置也无效，请问这是为什么？

**Comment by GitOfZGT** [comment]
热更新问题，修改主题变量文件未重新生成这些参数， v1.4.4 已修复。

![hmr var](https://user-images.githubusercontent.com/21262000/148019589-8fa3568b-ea12-4f25-9dd7-177641d1090b.gif)

**Comment by AnyFork** [comment]
ok，多谢了
