### ISSUE TITLE
Creating multiple style files per scope vars

### ISSUE THREAD

**Issue by naftis** [GitOfZGT/vite-plugin-theme-preprocessor#27]
Hello, thanks for this plugin again.

```
    themePreprocessorPlugin({
      scss: {
        multipleScopeVars: [
          {
            scopeName: 'theme-primary',
            path: path.resolve('src/theme/primary-vars.scss'),
          },
          {
            scopeName: 'theme-client1',
            path: path.resolve('src/theme/primary-vars.scss'),
          },
          {
            scopeName: 'theme-client2',
            path: path.resolve('src/theme/primary-vars.scss'),
          },
          {
            scopeName: 'theme-client3',
            path: path.resolve('src/theme/client3-vars.scss'),
          },
        ],
        defaultScopeName: 'theme-primary',
        extract: true,
      },
    }),
  ],
  ```
  
This doesn't build `.css` files for every theme, as I get: `GET /assets/theme-client2.css net::ERR_ABORTED 404 (Not Found)`.
Am I doing it wrong, or should I create multiple files with different paths? (with symlink for example)

**Comment by GitOfZGT** [comment]
It working well in my demo.  https://github.com/GitOfZGT/dynamic-theme-demos .    

@zougt/vite-plugin-theme-preprocessor v1.4.4  is  latest version.

![image](https://user-images.githubusercontent.com/21262000/149319236-77775faf-9762-4477-98a5-dbeff890f235.png)

**Comment by GitOfZGT** [comment]
> This doesn't build `.css` files for every theme, as I get: `GET /assets/theme-client2.css net::ERR_ABORTED 404 (Not Found)`. Am I doing it wrong, or should I create multiple files with different paths? (with symlink for example)

I was wrong.

Yes, you need  different paths.  and different  SASS var values.

![image](https://user-images.githubusercontent.com/21262000/149320865-9e0e7cfa-a635-4475-8786-2aefba3a3c58.png)

**Comment by GitOfZGT** [comment]
If you have to, you can try to adjust the order:  

![image](https://user-images.githubusercontent.com/21262000/149321736-02800cd0-2ac2-4747-adca-cfb6bd32d1ac.png)

**Comment by naftis** [comment]
Would it be possible if every multipleScopeVar would generate their own css-file? 

Consider my use case: 3 different companies use my application. Company 1 and Company 2 have unique themes. Company 3 uses the same theme as Company 1.
I can say this in my JavaScript client bundle:
```
if (route.params.company === "Company 3") {
  useTheme("Company 1")
} else {
  useTheme(route.params.company);
}
```
But note; in this case my client bundle would leak customer information for everyone to see. If someone were to look at my client source code, they would know that I have Company 1 and Company 3 in my application.

If every multipleScopeVar was to generate their own css-file, I could just say:
```
useTheme(route.params.company);
```
---
That being said; I can also work around this issue by creating symlink. If you think this is not worth implementing, the symlink way is also easy.
![image](https://user-images.githubusercontent.com/1322608/149327052-258a20b5-11d0-467b-947f-7851056610a4.png)

**Comment by GitOfZGT** [comment]
First file must different others.  It working.

![image](https://user-images.githubusercontent.com/21262000/149330651-59d3b64f-2f0f-4714-b845-159701bb64c3.png)
