### ISSUE TITLE
qiankun 下 toggleTheme 失效

### ISSUE THREAD

**Issue by transtone** [GitOfZGT/vite-plugin-theme-preprocessor#28]
之前的版本(1.4.0)在qiankun的子应用下使用是没什么问题的，但更新之后，1.4.2-1.4.4 都不能正常的在 html 中写入 class 了，导致样式失效。

**Comment by transtone** [comment]
很奇怪，给 html 加了一个 class 之后，又可以切换了。

**Comment by GitOfZGT** [comment]
> 很奇怪，给 html 加了一个 class 之后，又可以切换了。

我修改过toggleTheme里面切换classname方式，有正则匹配，你这么说，我再去review代码，这个确实是小bug，正则未考虑完全。
