### ISSUE TITLE
请问有没有更新日志

### ISSUE THREAD

**Issue by balck-paint** [GitOfZGT/vite-plugin-theme-preprocessor#29]
我看到更新了几个小版本，正好我的项目整体升级，也把这个更新到最新版本了，但是没找到更新日志不知道有没有需要改动的

**Comment by GitOfZGT** [comment]
有零散的提交记录，没详细记录。版本号遵循语意规范，新增内容和修复bug，不会删减功能，目前所支持的功能按照文档描述所体现的那样。之后的版本号，我有时间会写一个更新日志，尤其大版本破坏性更新等情况。
