### ISSUE TITLE
自定义主题文件引入ant-design-vue官方主题文件时报错

### ISSUE THREAD

**Issue by Nakus0426** [GitOfZGT/vite-plugin-theme-preprocessor#3]
我又来了。。。
这次是引入官方的暗色less文件时报错。在覆盖某些官方变量时也会报这个错误，比如@text-color。
引入“node_modules/ant-design-vue/lib/style/themes/dark.less”时报错如下
![image](https://user-images.githubusercontent.com/41540888/132300206-3a27e635-c159-4e88-888c-d5b00b2c5f8d.png)

**Comment by GitOfZGT** [comment]
按你的描述，我试了，没有报错，需要对应样本来确认
![image](https://user-images.githubusercontent.com/21262000/132494591-234f0902-99b8-4ba8-9c8c-a5ac959116d4.png)

**Comment by Nakus0426** [comment]
会不会是我使用了一个按需加载的插件（unplugin-vue-components）的原因
或者是我less版本过高（我用的是4.1.1）
下面是我的简单demo
[zhdt_web.zip](https://github.com/GitOfZGT/vite-plugin-theme-preprocessor/files/7129479/zhdt_web.zip)

**Comment by GitOfZGT** [comment]
> 会不会是我使用了一个按需加载的插件（unplugin-vue-components）的原因
> 或者是我less版本过高（我用的是4.1.1）
> 下面是我的简单demo
> [zhdt_web.zip](https://github.com/GitOfZGT/vite-plugin-theme-preprocessor/files/7129479/zhdt_web.zip)

跟less和其他插件无关，放心使用，我对编译后的css分析找到了原因，已在 @zougt/some-loader-utils v1.2.2 修复了
![image](https://user-images.githubusercontent.com/21262000/132606718-c36b618f-97be-4faa-94c3-f3d76ee1940d.png)

**Comment by Nakus0426** [comment]
已解决，感谢
