### ISSUE TITLE
error when load new css

### ISSUE THREAD

**Issue by qingtiantongxie** [GitOfZGT/vite-plugin-theme-preprocessor#31]
use toggleTheme to change the theme in my project
and got an error 
`browser-utils.js?v=615a3dac:73          GET http://192.168.0.105:3000/assets/black.css net::ERR_ABORTED 404 (Not Found)`

<img width="569" alt="image" src="https://user-images.githubusercontent.com/24731632/155514817-ea6d3976-1d64-4bbf-bcee-0a79be3c49d9.png">

the theme variable has changed， but body‘s classname didn't

**Comment by GitOfZGT** [comment]
Tell me the plugin version and options，or  check  the demos reproduces the problem ：https://github.com/GitOfZGT/dynamic-theme-demos

**Comment by qingtiantongxie** [comment]
it's very strange,  when i open my project in fireFox, it's totally ok, but not work in chrome,  and i checked the ant vue preset demo , it works in both! 

I found that in chrome, when i use toggleTheme function , it makes the following requests
<img width="986" alt="image" src="https://user-images.githubusercontent.com/24731632/155651954-8e5a9e0e-68bd-4087-a078-b35a11b7c17d.png">

and creates link labels like this : `<link rel="stylesheet" href="/assets/white.css" id="theme-link-tag_old">`

i don't get it ,  but i guess maybe it related to the operating environment ?like dev or product?

plugin version :
```
     "ant-design-vue": "^3.0.0-beta.4",
    "@vitejs/plugin-vue": "^1.9.3",
    "@zougt/vite-plugin-theme-preprocessor": "^1.4.0",
    "unplugin-vue-components": "^0.17.9",
    "less": "^4.1.2",
    "vite": "^2.7.2",
    "vue": "^3.2.25"
```

**Comment by GitOfZGT** [comment]
Please give me a demo, I can't reproduce it in my demo.

**Comment by qingtiantongxie** [comment]
It seems that I have solved the problem, although I don't know where the bug is. Thank you very much
