### ISSUE TITLE
[vite] Internal server error: Preprocessor dependency "less" not found. Did you install it?

### ISSUE THREAD

**Issue by hayabusa2009** [GitOfZGT/vite-plugin-theme-preprocessor#32]
### 使用yarn安装依赖，demo可以正常运行，但是pnpm会出现以下错误，请求帮忙（pnpm版本：7.0.0-alpha.0）

1. cd **vite-antd-vue-preset-theme**
2. pnpm install
3. pnpm dev

报错如下图
![image](https://user-images.githubusercontent.com/28643492/155678657-d633ea2d-8a75-4d99-ab81-dd8848f977bf.png)

5. pnpm add @zougt/some-loader-utils
6. pnpm dev

报错如下图
![image](https://user-images.githubusercontent.com/28643492/155678457-ad31211d-3eac-45cd-977f-9bd1a147b497.png)

**Comment by GitOfZGT** [comment]
确实是的，用pnpm@6.x 没有问题， 7.x会报错，在排查原因

**Comment by hayabusa2009** [comment]
感谢回复！我先降到6.X
请问我在预设主题模式下，可以动态修改主题色吗？比如我在theme-default主题下，动态修改primaryColor。

**Comment by GitOfZGT** [comment]
> 感谢回复！我先降到6.X 请问我在预设主题模式下，可以动态修改主题色吗？比如我在theme-default主题下，动态修改primaryColor。

还在 v1.5.0 规划与实现这个功能中...

**Comment by hayabusa2009** [comment]
非常感谢，我先把issue关掉了
