### ISSUE TITLE
启动服务时太慢 

### ISSUE THREAD

**Issue by XuJin186** [GitOfZGT/vite-plugin-theme-preprocessor#33]
请问是否有优化的可能？

**Comment by GitOfZGT** [comment]
less/scss文件越多编译越慢， 如果用预设主题模式，变量文件越多，编译越慢。 如果是demo感觉很慢，确实是，发现使用了unplugin-vue-components， 和不使用 unplugin-vue-components ，首次启动感觉有差距。

**Comment by GitOfZGT** [comment]
有网友发现 [vite-plugin-optimize-persist](https://www.npmjs.com/package/vite-plugin-optimize-persist) 可以提升下次启动的依赖优化。看看能否帮到你。

**Comment by XuJin186** [comment]
你好 我想请教一下非此项目的问题     我是react和 antd   dev的时候样式正常   但是build之后出现css权重问题  样式错乱   不是全部  只是极个别的   我可以付费请教

**Comment by XuJin186** [comment]
> 有网友发现 [vite-plugin-optimize-persist](https://www.npmjs.com/package/vite-plugin-optimize-persist) 可以提升下次启动的依赖优化。看看能否帮到你。

经过测试并没有明显的改善

**Comment by savelifeme** [comment]
> > 有网友发现 [vite-plugin-optimize-persist](https://www.npmjs.com/package/vite-plugin-optimize-persist) 可以提升下次启动的依赖优化。看看能否帮到你。
> 
> 经过测试并没有明显的改善

遇到同样的问题了，默认主题启动速度还能接受，但是主题越多，启动服务就越慢，有解决方案吗？
