### ISSUE TITLE
不支持3.x版本的antdesign for vue

### ISSUE THREAD

**Issue by zwd862375698** [GitOfZGT/vite-plugin-theme-preprocessor#34]
如题

**Comment by GitOfZGT** [comment]
支持的，跟支不支持组件库无关，跟是否使用less/sass有关。
![image](https://user-images.githubusercontent.com/21262000/159172279-0f5689d8-ecfa-4b59-9ebc-0728753d173e.png)

**Comment by GitOfZGT** [comment]
我已将 [https://github.com/GitOfZGT/vite-dynamictheme-antd-vue-demo](https://github.com/GitOfZGT/vite-dynamictheme-antd-vue-demo) 改用ant-design-vue v3.x
