### ISSUE TITLE
vite打包前为什么会在css前面增加一个/

### ISSUE THREAD

**Issue by Aa805837680** [GitOfZGT/vite-plugin-theme-preprocessor#36]
<link rel="modulepreload" href="./assets/vendor.0aafb233.js">
<link rel="stylesheet" href="./assets/index.bfd0df5f.css">
<link rel="stylesheet" href="/./static/theme-default.css" id="theme-link-tag">

**Comment by Aa805837680** [comment]
![微信图片_20220413104959](https://user-images.githubusercontent.com/46232995/163090370-a3cb8130-ec6d-42a5-9280-a7467f05d1ee.png)
#

**Comment by GitOfZGT** [comment]
用的相对路径来部署的么，我看下吧，没试过相对路径打包。

**Comment by Aa805837680** [comment]
> 
是的 谢谢 大佬

**Comment by GitOfZGT** [comment]
v1.4.5已处理
