### ISSUE TITLE
多种主题 primary-color 不能相同，是有什么限制吗

### ISSUE THREAD

**Issue by echooys** [GitOfZGT/vite-plugin-theme-preprocessor#39]

**Comment by GitOfZGT** [comment]
例如你提供了5个vars文件， 后面的4个vars编译后的css，始终会与第1个vars编译的css对比，抽取出差异的主题css，所以只要保证第1个的vars里面的primary-color与其他vars里面的priamry-color不同，就会生效。

**Comment by echooys** [comment]
> 例如文件，后面提供了 54 个主题编译后的 css，会与第 1 个vars 的 css 对比，不同出差异的 css，所以只要保证第 1 个 vars 里面的原始 - color 和其他vars里面的primamry-color不同，一直有效。

3q，懂了
