### ISSUE TITLE
vite less 文件不能自定义变量

### ISSUE THREAD

**Issue by sanjinhub** [GitOfZGT/vite-plugin-theme-preprocessor#43]
<img width="596" alt="image" src="https://user-images.githubusercontent.com/53846155/168280990-a16155a1-0a63-4aad-af67-84367eb28996.png">

<img width="776" alt="image" src="https://user-images.githubusercontent.com/53846155/168281048-3e9724ea-1f8f-4fc0-8e95-c009c575f34a.png">

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/53846155/168281130-8da1a211-8432-4499-8279-6467859254ea.png">

不知道为什么获取不到变量，引入 @import xxxx.less 是可以的，但是这样搞，不就不能动态切换了？

**Comment by GitOfZGT** [comment]
要把自定义的less，写在另外的文件，我在demo的注释有些说明
![image](https://user-images.githubusercontent.com/21262000/168282001-f8296ba5-9207-45be-a73a-0e4402e56cf9.png)

**Comment by GitOfZGT** [comment]
意思是， @test-color:#ccc; 写在 a.less,  然后哪里需要 就 @import "a.less";
![image](https://user-images.githubusercontent.com/21262000/168289015-1c4a3859-362b-48ad-864c-adfa07bed33f.png)

**Comment by sanjinhub** [comment]
我知道这样是可以的，但是这样，无法动态切换了。如果自己写个，那就需要和大佬的插件出现两个切换主题的功能了。

**Comment by GitOfZGT** [comment]
> 我知道这样是可以的，但是这样，无法动态切换了。如果自己写个，那就需要和大佬的插件出现两个切换主题的功能了。

支持的，@test-color:#ccc; 写在 a.less,     @test-color:#888; 写在 theme/default.less,  切换用
```js
setCustomTheme({
     primary:"#878787", 
     gradientReplacer:{'#888':'#999'}
})
```

**Comment by sanjinhub** [comment]
我是这样干的，直接在 main.ts 全局引入 import "./theme/default.less"; ，然后就搞定了。
感谢作者，插件很棒，有赞赏的地方吗？

**Comment by GitOfZGT** [comment]
> 我是这样干的，直接在 main.ts 全局引入 import "./theme/default.less"; ，然后就搞定了。 感谢作者，插件很棒，有赞赏的地方吗？

没有，谢谢，多反馈问题就足矣！哈哈
