### ISSUE TITLE
自定义主题 按钮主题丢失

### ISSUE THREAD

**Issue by pengyinghao** [GitOfZGT/vite-plugin-theme-preprocessor#47]
ant design vue：3.2.9
vite:3.2.25

自定义了主题后，按钮的样式被覆盖并没有重写
<img width="626" alt="image" src="https://user-images.githubusercontent.com/34115313/177695570-0896b495-b8e3-496d-8a33-f7ee65b2ccff.png">

<img width="1527" alt="image" src="https://user-images.githubusercontent.com/34115313/177695632-eaa30359-62f9-4e18-9470-c2afcc92b774.png">

**Comment by pengyinghao** [comment]
但是只有556ff6 这个颜色有这个问题。
大佬有时间的话可以看一下，我把仓库放在这 ```https://github.com/pengyinghao/test```

**Comment by pengyinghao** [comment]
> 预设主题的编译原理：在编译某个less文件时，提供给multipleScopeVars内的几个less变量，会与这个less文件合并后编译出多个css，这几个css对比后抽取出不相同的主题css。
> 
> 不清楚你的配置是怎样的，你知晓原理后进行排查问题。

我好像发现了问题，如果两个预设的两个主题 色彩相同的话就有这个问题。如果不相同就不会发生这种情况

**Comment by pengyinghao** [comment]
> 预设主题的编译原理：在编译某个less文件时，提供给multipleScopeVars内的几个less变量，会与这个less文件合并后编译出多个css，这几个css对比后抽取出不相同的主题css。
> 
> 不清楚你的配置是怎样的，你知晓原理后进行排查问题。

在测试中，我发现了如果亮色 和暗黑 设置相同的 主题色，就会发生此问题，如果不相同则正常。大佬有时间的话 帮忙看一下啊！！
仓库地址：```https://github.com/pengyinghao/test```

**Comment by GitOfZGT** [comment]
只要是multipleScopeVars的第一个主题色与其他的不相同就行

**Comment by pengyinghao** [comment]
那这种处理不到咯。如果暗色 和亮色都需要同样的主题

**Comment by GitOfZGT** [comment]
你可以加三个.less,   第一个less变量与其他两个不一样，其他两个可以相同

**Comment by pengyinghao** [comment]
谢谢，后续可能会考虑这种 。
