### ISSUE TITLE
在阿里云效构建，出现，Preprocessor dependency "less" not found. Did you install it

### ISSUE THREAD

**Issue by jekip** [GitOfZGT/vite-plugin-theme-preprocessor#8]
本地构建没有这个问题，这个似乎和，文档描述的，`resetStylePreprocessor` 有点关系，云效构建使用的是 `cnpm` 排查了一下`@zougt/vite-plugin-theme-preprocessor` 这个包也是最新的，如何去排查或者解决这种问题？

**Comment by jekip** [comment]
有空帮忙，看一下这个，谢谢

**Comment by GitOfZGT** [comment]
cnpm install 生成的node_modules目录结构差异有点大，如果紧急使用，请改用yarn或其他安装方式，有空我再兼容cnpm install

**Comment by GitOfZGT** [comment]
@zougt/vite-plugin-theme-preprocessor v1.3.5 has fixed

**Comment by jekip** [comment]
> @zougt/vite-plugin-theme-preprocessor v1.3.5 has fixed

尝试升级到最新版本，在云效构建，用 `yarn` 和 `cnpm` 方式构建，都报一样的错误，`[vite-plugin-theme-preprocessor] ENOENT: no such file or directory, stat`

早期 `1.3.4`  我用 `yarn` 是正常打包的，如今我退回依然不行，这个插件和根目录下面，`yarn.lock ` 有关系吗？

因为想换 `pnpm` 构建，`yarn.lock` 文件自然是想删除的，但是不影响云效那边构建，唯独这个插件报错了，目前只能在本地手动打包构建，没有出现报错

这个路径的问题，有没有比较好的方式解决，因为类似场景可能还有很多

**Comment by GitOfZGT** [comment]
如果package.json的依赖@zougt/vite-plugin-theme-preprocessor版本改变了，尝试删除node_modules和yarn.lock 后再安装

**Comment by GitOfZGT** [comment]
报错信息，截图完整的让我看看

**Comment by jekip** [comment]
> 报错信息，截图完整的让我看看

![QQ截图20211110175257](https://user-images.githubusercontent.com/19426584/141118669-ccee5a78-e8ec-4c15-8573-bd09e02a3a18.png)
